server:
  port: 8081
spring:
  application:
    name: ShortVideos


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/my-comment?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678

  redis:
    host: 192.168.23.128
    port: 6379
    password: 12345678
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

  jackson:
    default-property-inclusion: non_null

mybatis-plus:
  type-aliases-package: org.example.entity
  mapper-locations: classpath:/mapper/*.xml


logging:
  level:
    org.example: debug



